"""Génération de livrables (cahier §5) : lettre d'engagement, NDA, rapport PTES.

Chaîne : gabarit HTML → PDF via Chromium headless (service `pdf-renderer` du
compose). Règles de sécurité :
  - TLP/client marqués en pied de page (bandeau de classification) ;
  - les preuves marquées `contains_secrets` ne sont JAMAIS intégrées en clair :
    on insère un marqueur masqué + renvoi vers la custody (spec preuves, porte 5).
Le rendu tourne sous le rôle de service `report_render` (périmètre minimal).
"""
from __future__ import annotations

import html
from datetime import UTC, datetime

from fastapi import FastAPI, Response
from pydantic import BaseModel

_TLP_COLORS = {
    "RED": "#D32F2F",
    "AMBER": "#F59E0B",
    "AMBER+STRICT": "#B45309",
    "GREEN": "#2E7D32",
    "CLEAR": "#455A64",
}

# ── Internationalisation des gabarits (fr/en) ────────────────────────────────
# Seuls les libellés/titres/clauses fixes AUTORÉS ici sont traduits. Le contenu
# dynamique (données d'audit, texte libre saisi dans le bloc engagement, constats)
# est rendu tel quel, dans la langue où il a été rédigé.
_LABELS: dict[str, dict[str, str]] = {
    # Communs
    "yes": {"fr": "Oui", "en": "Yes"},
    "footer_parties": {
        "fr": "Document généré par Purple Cockpit — TLP:{tlp} — diffusion restreinte aux parties",
        "en": "Generated by Purple Cockpit — TLP:{tlp} — restricted distribution to the parties",
    },
    "footer_client": {
        "fr": "TLP:{tlp} — diffusion restreinte au client — généré par Purple Cockpit",
        "en": "TLP:{tlp} — restricted distribution to the client — generated by Purple Cockpit",
    },
    # Bloc signatures
    "sig_provider": {"fr": "Pour le prestataire — {name}", "en": "For the provider — {name}"},
    "sig_client": {"fr": "Pour le client — {name}", "en": "For the client — {name}"},
    "sig_line": {"fr": "Nom, fonction, date et signature :", "en": "Name, role, date and signature:"},
    # Registre de preuves
    "ev_masked": {
        "fr": "[preuve masquée — voir chaîne de custody]",
        "en": "[masked evidence — see chain of custody]",
    },
    "ev_fallback_name": {"fr": "preuve", "en": "evidence"},
    "ev_empty": {
        "fr": "Aucune preuve stockée pour cet audit.",
        "en": "No evidence stored for this audit.",
    },
    "ev_th_ts": {"fr": "Horodatage (dépôt)", "en": "Timestamp (upload)"},
    "ev_th_name": {"fr": "Nom de fichier", "en": "File name"},
    "ev_th_mime": {"fr": "Type MIME", "en": "MIME type"},
    "ev_th_hash": {"fr": "Empreinte SHA-256 (clair)", "en": "SHA-256 digest (plaintext)"},
    "ev_th_size": {"fr": "Taille", "en": "Size"},
    "ev_th_by": {"fr": "Déposé par", "en": "Uploaded by"},
    # Lettre d'engagement
    "eng_title": {"fr": "Lettre d'engagement", "en": "Engagement letter"},
    "eng_meta": {
        "fr": "Mission : {nom} — Catégorie {cat}{tt} · Référentiels : {refs}",
        "en": "Engagement: {nom} — Category {cat}{tt} · Frameworks: {refs}",
    },
    "eng_h_parties": {"fr": "Parties", "en": "Parties"},
    "eng_kv_provider": {"fr": "Prestataire", "en": "Provider"},
    "eng_kv_client": {"fr": "Client", "en": "Client"},
    "eng_kv_siren": {"fr": " — SIREN {siren}", "en": " — reg. no. {siren}"},
    "eng_kv_sector": {"fr": "Secteur du client", "en": "Client sector"},
    "eng_kv_contact": {"fr": "Référent client", "en": "Client point of contact"},
    "eng_kv_sow": {"fr": "Référence SOW", "en": "SOW reference"},
    "eng_kv_nda": {"fr": "Référence NDA", "en": "NDA reference"},
    "eng_kv_auth": {"fr": "Autorisation signée", "en": "Signed authorisation"},
    "eng_auth_no": {"fr": "Non — à signer avant tout test", "en": "No — to be signed before any testing"},
    "eng_callout": {
        "fr": "⚠ Aucun test ne peut démarrer avant la signature de la présente autorisation "
              "par un représentant habilité du client.",
        "en": "⚠ No testing may begin before this authorisation is signed by a duly "
              "empowered representative of the client.",
    },
    "eng_h_scope": {"fr": "Objectifs et périmètre", "en": "Objectives and scope"},
    "eng_h_objectives": {"fr": "Objectifs de la mission", "en": "Engagement objectives"},
    "eng_fb_objectives": {
        "fr": "Objectifs définis conjointement au cadrage.",
        "en": "Objectives defined jointly during scoping.",
    },
    "eng_h_incl": {"fr": "Périmètre inclus", "en": "In-scope perimeter"},
    "eng_fb_incl": {"fr": "Périmètre détaillé en annexe du SOW.", "en": "Detailed scope in the SOW annex."},
    "eng_h_excl": {"fr": "Périmètre explicitement exclu", "en": "Explicitly out-of-scope"},
    "eng_fb_excl": {
        "fr": "Aucune exclusion déclarée — toute cible hors périmètre inclus reste proscrite.",
        "en": "No exclusion declared — any target outside the in-scope perimeter remains prohibited.",
    },
    "eng_h_apps": {"fr": "Applications ciblées", "en": "Target applications"},
    "eng_fb_apps": {
        "fr": "Aucune application référencée — voir périmètre ci-dessus.",
        "en": "No application referenced — see scope above.",
    },
    "eng_th_app": {"fr": "Application", "en": "Application"},
    "eng_th_version": {"fr": "Version", "en": "Version"},
    "eng_th_crit": {"fr": "Criticité", "en": "Criticality"},
    "eng_th_expo": {"fr": "Exposition", "en": "Exposure"},
    "eng_th_env": {"fr": "Environnement", "en": "Environment"},
    "eng_h_scenario": {"fr": "Scénario de menace émulé", "en": "Emulated threat scenario"},
    "eng_kv_scenario": {"fr": "Scénario", "en": "Scenario"},
    "eng_kv_actor": {"fr": "Acteur émulé", "en": "Emulated actor"},
    "eng_kv_engtype": {"fr": "Type d'engagement", "en": "Engagement type"},
    "eng_kv_sophis": {"fr": "Sophistication", "en": "Sophistication"},
    "eng_kv_objective": {"fr": "Objectif", "en": "Objective"},
    "eng_h_ttp": {"fr": "Techniques MITRE ATT&amp;CK couvertes", "en": "MITRE ATT&amp;CK techniques covered"},
    "eng_h_windows": {"fr": "Fenêtres d'intervention", "en": "Intervention windows"},
    "eng_kv_dates": {"fr": "Dates de la mission", "en": "Engagement dates"},
    "eng_kv_intensity": {"fr": "Niveau d'intensité", "en": "Intensity level"},
    "eng_intensity_std": {"fr": "Standard", "en": "Standard"},
    "eng_h_windows_ok": {"fr": "Fenêtres de test autorisées", "en": "Authorised testing windows"},
    "eng_fb_windows": {
        "fr": "Fenêtres à convenir avec les contacts d'autorisation.",
        "en": "Windows to be agreed with the authorisation contacts.",
    },
    "eng_h_roe": {"fr": "Règles d'engagement", "en": "Rules of engagement"},
    "eng_fb_roe": {
        "fr": "Conformité {refs}. Toute action hors périmètre est proscrite. Les preuves "
              "collectées sont chiffrées, horodatées et conservées selon la politique de rétention.",
        "en": "Compliance with {refs}. Any out-of-scope action is prohibited. Collected evidence "
              "is encrypted, timestamped and retained per the retention policy.",
    },
    "eng_h_contacts": {"fr": "Contacts", "en": "Contacts"},
    "eng_h_contacts_auth": {"fr": "Contacts d'autorisation", "en": "Authorisation contacts"},
    "eng_fb_contacts": {"fr": "À désigner avant le démarrage.", "en": "To be designated before kickoff."},
    "eng_h_contacts_urg": {
        "fr": "Contacts d'urgence (arrêt immédiat)",
        "en": "Emergency contacts (immediate stop)",
    },
    "eng_h_team": {"fr": "Équipe d'audit assignée", "en": "Assigned audit team"},
    "eng_th_member": {"fr": "Intervenant", "en": "Team member"},
    "eng_th_role": {"fr": "Rôle", "en": "Role"},
    "eng_th_skills": {"fr": "Compétences", "en": "Skills"},
    "eng_th_contact": {"fr": "Contact", "en": "Contact"},
    "eng_fb_team": {
        "fr": "Équipe communiquée avant le démarrage de la mission.",
        "en": "Team communicated before the engagement starts.",
    },
    "eng_h_deliverables": {"fr": "Livrables attendus", "en": "Expected deliverables"},
    "eng_fb_deliverables": {
        "fr": "Rapport de mission et restitution — liste détaillée au SOW.",
        "en": "Engagement report and debrief — detailed list in the SOW.",
    },
    "eng_h_legal": {"fr": "Clauses légales", "en": "Legal clauses"},
    "eng_fb_legal": {
        "fr": "Les tests sont réalisés dans le strict cadre de l'autorisation ci-dessus. Le "
              "prestataire s'engage à la confidentialité (voir NDA référencé) et à la "
              "non-destruction ; le client garantit être titulaire des droits sur les systèmes ciblés.",
        "en": "Testing is performed strictly within the authorisation above. The provider commits "
              "to confidentiality (see referenced NDA) and non-destruction; the client warrants it "
              "holds the rights over the targeted systems.",
    },
    # NDA
    "nda_title": {"fr": "Accord de confidentialité (NDA)", "en": "Non-Disclosure Agreement (NDA)"},
    "nda_meta": {"fr": "Rattaché à la mission : {mission}", "en": "Attached to engagement: {mission}"},
    "nda_h_parties": {"fr": "Parties", "en": "Parties"},
    "nda_kv_role": {
        "fr": "Partie divulgatrice / réceptrice",
        "en": "Disclosing / receiving party",
    },
    "nda_role_recip": {
        "fr": "Réciproque — chaque partie est tour à tour divulgatrice et réceptrice",
        "en": "Reciprocal — each party is in turn disclosing and receiving",
    },
    "nda_kv_provider": {"fr": "Prestataire", "en": "Provider"},
    "nda_kv_client": {"fr": "Client", "en": "Client"},
    "nda_kv_ref": {"fr": "Référence", "en": "Reference"},
    "nda_h_object": {"fr": "Objet et informations confidentielles", "en": "Purpose and confidential information"},
    "nda_fb_object": {
        "fr": "Sont confidentielles toutes informations techniques, organisationnelles ou "
              "commerciales échangées dans le cadre de la mission : architecture, vulnérabilités "
              "découvertes, preuves d'exploitation, identifiants, données métier, ainsi que "
              "l'existence et le contenu des livrables.",
        "en": "Confidential information means any technical, organisational or commercial "
              "information exchanged during the engagement: architecture, discovered "
              "vulnerabilities, exploitation evidence, credentials, business data, as well as "
              "the existence and content of the deliverables.",
    },
    "nda_h_duration": {"fr": "Durée", "en": "Duration"},
    "nda_fb_duration": {
        "fr": "Les obligations de confidentialité s'appliquent pendant la mission et perdurent "
              "après son terme, y compris après restitution ou destruction des informations.",
        "en": "Confidentiality obligations apply during the engagement and survive its "
              "termination, including after return or destruction of the information.",
    },
    "nda_h_treatment": {
        "fr": "Traitement et protection des informations",
        "en": "Handling and protection of information",
    },
    "nda_fb_treatment": {
        "fr": "Les informations sont marquées et manipulées selon le protocole TLP (Traffic Light "
              "Protocol) ; les preuves sont chiffrées, horodatées et stockées dans un coffre "
              "inaltérable avec journal d'accès nominatif. L'accès est limité au strict besoin "
              "d'en connaître au sein de l'équipe assignée.",
        "en": "Information is marked and handled according to the TLP (Traffic Light Protocol); "
              "evidence is encrypted, timestamped and stored in a tamper-proof vault with a "
              "named-access log. Access is limited to a strict need-to-know within the assigned team.",
    },
    "nda_h_return": {"fr": "Restitution et destruction", "en": "Return and destruction"},
    "nda_fb_return": {
        "fr": "En fin de mission, les informations confidentielles sont restituées ou détruites "
              "par crypto-effacement (destruction des clés de chiffrement), la trace de "
              "destruction restant journalisée sans le contenu.",
        "en": "At the end of the engagement, confidential information is returned or destroyed by "
              "crypto-shredding (destruction of the encryption keys), the destruction record "
              "remaining logged without the content.",
    },
    "nda_h_law": {"fr": "Droit applicable", "en": "Governing law"},
    "nda_fb_law": {
        "fr": "Le présent accord est régi par le droit applicable convenu entre les parties ; "
              "tout litige relève des juridictions compétentes du ressort du client.",
        "en": "This agreement is governed by the law agreed between the parties; any dispute "
              "falls under the competent courts of the client's jurisdiction.",
    },
    "nda_h_tlp": {"fr": "Marquage TLP de la mission", "en": "Engagement TLP marking"},
    "nda_tlp_body": {
        "fr": "Sauf mention contraire par document, les échanges de la mission sont marqués "
              "<strong>TLP:{tlp}</strong> — la diffusion suit strictement les règles de ce niveau.",
        "en": "Unless otherwise stated per document, engagement exchanges are marked "
              "<strong>TLP:{tlp}</strong> — distribution strictly follows the rules of that level.",
    },
    # Rapport PTES
    "rpt_title": {"fr": "Rapport Purple Team", "en": "Purple Team report"},
    "rpt_meta": {"fr": "{nom} — {client} — généré par {presta}", "en": "{nom} — {client} — generated by {presta}"},
    "rpt_h_mission": {"fr": "Fiche de mission", "en": "Engagement summary"},
    "rpt_kv_client": {"fr": "Client", "en": "Client"},
    "rpt_kv_provider": {"fr": "Prestataire", "en": "Provider"},
    "rpt_kv_cat": {"fr": "Catégorie / type de test", "en": "Category / test type"},
    "rpt_kv_refs": {"fr": "Référentiels", "en": "Frameworks"},
    "rpt_kv_period": {"fr": "Période", "en": "Period"},
    "rpt_kv_env": {"fr": "Environnement", "en": "Environment"},
    "rpt_kv_team": {"fr": "Équipe d'audit", "en": "Audit team"},
    "rpt_kv_status": {"fr": "Statut de l'audit", "en": "Audit status"},
    "rpt_h_summary": {"fr": "Synthèse", "en": "Summary"},
    "rpt_no_vuln": {"fr": "Aucune vulnérabilité enregistrée", "en": "No vulnerability recorded"},
    "rpt_h_actions": {"fr": "Actions d'audit réalisées", "en": "Audit actions performed"},
    "rpt_th_phase": {"fr": "Phase PTES", "en": "PTES phase"},
    "rpt_th_action": {"fr": "Action", "en": "Action"},
    "rpt_th_tool": {"fr": "Outil", "en": "Tool"},
    "rpt_th_result": {"fr": "Résultat", "en": "Result"},
    "rpt_h_scenario": {"fr": "Scénario de menace émulé", "en": "Emulated threat scenario"},
    "rpt_kv_scenario": {"fr": "Scénario", "en": "Scenario"},
    "rpt_kv_actor": {"fr": "Acteur émulé", "en": "Emulated actor"},
    "rpt_kv_sophis": {"fr": "Sophistication", "en": "Sophistication"},
    "rpt_kv_objective": {"fr": "Objectif", "en": "Objective"},
    "rpt_h_apps": {"fr": "Périmètre applicatif", "en": "Application perimeter"},
    "rpt_th_app": {"fr": "Application", "en": "Application"},
    "rpt_th_crit": {"fr": "Criticité", "en": "Criticality"},
    "rpt_th_expo": {"fr": "Exposition", "en": "Exposure"},
    "rpt_th_stack": {"fr": "Stack", "en": "Stack"},
    "rpt_h_vulns": {"fr": "Vulnérabilités", "en": "Vulnerabilities"},
    "rpt_th_vuln": {"fr": "Vulnérabilité", "en": "Vulnerability"},
    "rpt_th_sev": {"fr": "Sévérité", "en": "Severity"},
    "rpt_th_status": {"fr": "Statut", "en": "Status"},
    "rpt_none": {"fr": "Aucune", "en": "None"},
    "rpt_h_evidence": {"fr": "Registre des preuves", "en": "Evidence register"},
    "rpt_evidence_note": {
        "fr": "Registre de custody : chaque preuve est scellée dans le coffre WORM (chiffrement "
              "AES-256-GCM, empreinte SHA-256 du clair pour l'intégrité, horodatage et journal "
              "d'accès nominatif). Les preuves contenant des secrets voient leur nom masqué dans "
              "ce document — leurs métadonnées d'intégrité restent auditables ; le contenu n'est "
              "consultable que via la chaîne de custody tracée.",
        "en": "Chain-of-custody register: each item is sealed in the WORM vault (AES-256-GCM "
              "encryption, SHA-256 plaintext digest for integrity, timestamp and named-access "
              "log). Items containing secrets have their name masked in this document — their "
              "integrity metadata remains auditable; the content is only accessible via the "
              "tracked chain of custody.",
    },
    # Détail des vulnérabilités (une fiche par vuln)
    "vd_h_section": {"fr": "Détail des vulnérabilités", "en": "Vulnerability details"},
    "vd_none": {"fr": "Aucune vulnérabilité à détailler.", "en": "No vulnerability to detail."},
    "no": {"fr": "Non", "en": "No"},
    "vd_kv_cvss": {"fr": "Score CVSS", "en": "CVSS score"},
    "vd_kv_vector": {"fr": "Vecteur CVSS", "en": "CVSS vector"},
    "vd_kv_status": {"fr": "Statut", "en": "Status"},
    "vd_kv_exploit": {"fr": "Exploitabilité", "en": "Exploitability"},
    "vd_kv_phase": {"fr": "Phase de découverte", "en": "Discovery phase"},
    "vd_kv_discoverer": {"fr": "Découvreur", "en": "Discovered by"},
    "vd_kv_sla": {"fr": "SLA", "en": "SLA"},
    "vd_kv_sla_due": {"fr": "Échéance SLA", "en": "SLA due date"},
    "vd_kv_epss": {"fr": "EPSS", "en": "EPSS"},
    "vd_kv_kev": {"fr": "CISA KEV", "en": "CISA KEV"},
    "vd_kev_ransom": {"fr": "rançongiciel", "en": "ransomware"},
    "vd_kv_ssvc": {"fr": "Décision SSVC", "en": "SSVC decision"},
    "vd_kv_vex": {"fr": "Statut VEX", "en": "VEX status"},
    "vd_h_desc": {"fr": "Description", "en": "Description"},
    "vd_h_impact": {"fr": "Impact métier", "en": "Business impact"},
    "vd_h_proof": {"fr": "Preuve d'exploitation", "en": "Exploitation proof"},
    "vd_h_reco": {"fr": "Recommandation", "en": "Recommendation"},
    "vd_h_ttp": {"fr": "Techniques MITRE ATT&amp;CK", "en": "MITRE ATT&amp;CK techniques"},
    "vd_h_d3fend": {"fr": "Mesures défensives D3FEND", "en": "D3FEND defensive measures"},
    "vd_h_evidence": {"fr": "Preuves associées", "en": "Associated evidence"},
    "vd_no_evidence": {
        "fr": "Aucune preuve associée à cette vulnérabilité.",
        "en": "No evidence associated with this vulnerability.",
    },
    "vd_ev_th_preview": {"fr": "Aperçu", "en": "Preview"},
    "vd_ev_masked_preview": {"fr": "aperçu masqué", "en": "masked preview"},
    "vd_preview_limit": {
        "fr": "Les aperçus d'images sont intégrés en clair dans ce document jusqu'à {size} "
              "par preuve ; au-delà, la preuve est référencée par son empreinte SHA-256 sans "
              "être affichée. Les preuves marquées « secrets » ne sont jamais affichées en clair.",
        "en": "Image previews are embedded in clear in this document up to {size} per item; "
              "beyond that, the evidence is referenced by its SHA-256 digest without being "
              "displayed. Evidence flagged as containing secrets is never shown in clear.",
    },
}

# Unités de taille lisibles selon la langue.
_SIZE_UNITS = {"fr": ("o", "Kio", "Mio", "Gio"), "en": ("B", "KiB", "MiB", "GiB")}


def _t(langue: str, key: str) -> str:
    """Libellé traduit, repli sur le français si langue/clé absente."""
    entry = _LABELS.get(key, {})
    return entry.get(langue) or entry.get("fr") or key


def _banner(tlp: str, client_name: str) -> str:
    color = _TLP_COLORS.get(tlp.upper(), "#455A64")
    stamp = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")
    return (
        f'<div class="tlp-banner" style="background:{color}">'
        f"TLP:{html.escape(tlp)} — {html.escape(client_name)} — {stamp}"
        f"</div>"
    )


_BASE_CSS = """
<style>
  @page { margin: 24mm 18mm; }
  body { font-family: 'Inter', 'Helvetica Neue', Arial, sans-serif; color: #1A1626;
         font-size: 11pt; line-height: 1.5; }
  h1 { color: #4C1D95; font-size: 20pt; margin-bottom: 4px; }
  h2 { color: #6D28D9; font-size: 14pt; border-bottom: 2px solid #EDE9FE;
       padding-bottom: 4px; margin-top: 22px; }
  h3 { color: #4C1D95; font-size: 11.5pt; margin: 14px 0 4px; }
  h4 { color: #6D28D9; font-size: 10pt; margin: 10px 0 3px; }
  .tlp-banner { color: white; font-weight: 700; padding: 6px 12px; border-radius: 6px;
                text-align: center; letter-spacing: 0.06em; margin-bottom: 18px; }
  .meta { color: #6B6580; font-size: 9pt; }
  .masked { background: #EDE9FE; color: #6D28D9; padding: 2px 8px; border-radius: 4px;
            font-style: italic; }
  table { width: 100%; border-collapse: collapse; margin: 10px 0; }
  th, td { border: 1px solid #E5E1F0; padding: 6px 8px; text-align: left; font-size: 10pt; }
  th { background: #F4F2F9; color: #4C1D95; }
  table.kv td:first-child { width: 34%; background: #FBFAFD; color: #4C1D95;
                            font-weight: 600; }
  .sev-critique { color: #D32F2F; font-weight: 700; }
  .sev-haute { color: #E65100; font-weight: 600; }
  .footer { color: #9B95AD; font-size: 8pt; text-align: center; margin-top: 30px; }
  .callout { background: #FFF7E6; border: 1px solid #F2D399; border-radius: 6px;
             padding: 8px 12px; font-size: 10pt; margin: 10px 0; }
  .sig-row { display: flex; gap: 24px; margin-top: 36px; }
  .sig-box { flex: 1; border: 1px solid #E5E1F0; border-radius: 6px; padding: 12px;
             min-height: 90px; font-size: 9.5pt; color: #6B6580; }
  .sig-box b { color: #1A1626; display: block; margin-bottom: 28px; }
  ul.compact { margin: 4px 0 10px; padding-left: 20px; }
  ul.compact li { margin: 2px 0; }
  .pill { display: inline-block; border: 1px solid #DDD6F3; border-radius: 999px;
          padding: 1px 10px; font-size: 9pt; color: #4C1D95; background: #F4F2F9;
          margin-right: 4px; }
  .mono { font-family: 'IBM Plex Mono', 'Courier New', monospace; }
  .nowrap { white-space: nowrap; }
  table.evidence-register td, table.evidence-register th { font-size: 8.5pt; padding: 5px 6px;
          vertical-align: top; }
  table.evidence-register .hash .mono, table.vuln-evidence .hash .mono { font-size: 7.5pt;
          word-break: break-all; color: #4A4458; }
  table.evidence-register tbody tr:nth-child(even),
  table.vuln-evidence tbody tr:nth-child(even) { background: #FBFAFD; }
  .vuln-card { border: 1px solid #E5E1F0; border-radius: 8px; padding: 12px 14px; margin: 14px 0;
          page-break-inside: avoid; }
  .vuln-card h3 { margin-top: 0; }
  .vuln-card .sub { color: #6B6580; font-size: 9pt; margin: 2px 0 8px; }
  .vuln-prose { white-space: pre-wrap; font-size: 10pt; margin: 4px 0 10px; }
  table.vuln-evidence td, table.vuln-evidence th { font-size: 8.5pt; padding: 5px 6px;
          vertical-align: top; }
  .ev-preview { max-width: 220px; max-height: 160px; border: 1px solid #E5E1F0; border-radius: 4px; }
  .sev-badge { display: inline-block; border-radius: 999px; padding: 1px 10px; font-size: 9pt;
          font-weight: 700; color: white; }
  .sev-badge.critique { background: #D32F2F; } .sev-badge.haute { background: #E65100; }
  .sev-badge.moyenne { background: #C79100; } .sev-badge.basse { background: #2E7D32; }
  .sev-badge.info { background: #607D8B; }
</style>
"""


def _esc(v) -> str:
    """Échappe une valeur possiblement None/non-str."""
    return html.escape(str(v)) if v not in (None, "") else ""


def _dt(v) -> str:
    """Format lisible d'une date (str ISO ou date), '—' si absente."""
    if not v:
        return "—"
    return html.escape(str(v))


def _ul(items: list | None, empty: str = "—") -> str:
    """Liste HTML à partir d'une liste de chaînes (champ `lines` du bloc engagement)."""
    items = [i for i in (items or []) if str(i).strip()]
    if not items:
        return f"<p>{html.escape(empty)}</p>"
    lis = "".join(f"<li>{html.escape(str(i))}</li>" for i in items)
    return f'<ul class="compact">{lis}</ul>'


def _para(v, empty: str = "—") -> str:
    """Paragraphe(s) à partir d'un champ texte libre (retours ligne préservés)."""
    if not v or not str(v).strip():
        return f"<p>{html.escape(empty)}</p>"
    parts = [html.escape(p.strip()) for p in str(v).split("\n") if p.strip()]
    return "".join(f"<p>{p}</p>" for p in parts)


def _kv_table(rows: list[tuple[str, str]]) -> str:
    """Tableau clé/valeur pour les blocs de métadonnées."""
    trs = "".join(
        f"<tr><td>{html.escape(k)}</td><td>{v or '—'}</td></tr>" for k, v in rows
    )
    return f'<table class="kv"><tbody>{trs}</tbody></table>'


def _sig_block(prestataire: str, client: str, langue: str = "fr") -> str:
    """Bloc de signatures côte à côte (prestataire / client)."""
    line = html.escape(_t(langue, "sig_line"))
    provider = html.escape(_t(langue, "sig_provider").format(name=prestataire or "Prestataire"))
    client_lbl = html.escape(_t(langue, "sig_client").format(name=client))
    return (
        '<div class="sig-row">'
        f'<div class="sig-box"><b>{provider}</b>{line}</div>'
        f'<div class="sig-box"><b>{client_lbl}</b>{line}</div>'
        "</div>"
    )


def _mask_if_secret(item: dict, langue: str = "fr") -> str:
    """Une preuve `contains_secrets` n'apparaît jamais en clair dans un rapport."""
    if item.get("contains_secrets"):
        return f'<span class="masked">{html.escape(_t(langue, "ev_masked"))}</span>'
    fallback = _t(langue, "ev_fallback_name")
    return html.escape(item.get("caption") or item.get("original_filename", fallback))


def _human_size(n, langue: str = "fr") -> str:
    """Taille lisible (o/Kio/Mio/Gio en fr, B/KiB/MiB/GiB en en), '—' si absente."""
    if n in (None, ""):
        return "—"
    try:
        size = float(n)
    except (TypeError, ValueError):
        return "—"
    units = _SIZE_UNITS.get(langue, _SIZE_UNITS["fr"])
    for i, unit in enumerate(units):
        if size < 1024 or unit == units[-1]:
            return f"{size:.0f} {unit}" if i == 0 else f"{size:.1f} {unit}"
        size /= 1024
    return f"{size:.1f} {units[-1]}"


def _ts(v) -> str:
    """Horodatage forensique complet (date + heure UTC), '—' si absent."""
    if not v:
        return "—"
    s = str(v)
    # 'YYYY-MM-DDTHH:MM:SS...' ou 'YYYY-MM-DD HH:MM:SS...' → 'YYYY-MM-DD HH:MM:SS UTC'
    s = s.replace("T", " ")
    if "." in s:
        s = s.split(".", 1)[0]
    elif "+" in s:
        s = s.split("+", 1)[0]
    return html.escape(s.strip() + " UTC")


def _evidence_register(evidence: list[dict], langue: str = "fr") -> str:
    """Registre de preuves façon investigation numérique : une ligne par preuve avec
    horodatage, nom, type MIME, empreinte SHA-256, taille et déposant. Le nom des preuves
    `contains_secrets` est masqué ; les métadonnées d'intégrité (empreinte, taille,
    horodatage, déposant) restent visibles — elles ne révèlent pas le contenu."""
    if not evidence:
        return f"<p>{html.escape(_t(langue, 'ev_empty'))}</p>"
    rows = ""
    for e in evidence:
        sha = e.get("sha256_plaintext")
        sha_cell = f'<span class="mono">{html.escape(sha)}</span>' if sha else "—"
        rows += (
            "<tr>"
            f"<td class='mono nowrap'>{_ts(e.get('uploaded_at'))}</td>"
            f"<td>{_mask_if_secret(e, langue)}</td>"
            f"<td class='mono'>{_esc(e.get('detected_mime')) or '—'}</td>"
            f"<td class='hash'>{sha_cell}</td>"
            f"<td class='nowrap'>{_human_size(e.get('size_bytes'), langue)}</td>"
            f"<td>{_esc(e.get('uploaded_by_name')) or '—'}</td>"
            "</tr>"
        )
    return (
        '<table class="evidence-register"><thead><tr>'
        f"<th>{html.escape(_t(langue, 'ev_th_ts'))}</th>"
        f"<th>{html.escape(_t(langue, 'ev_th_name'))}</th>"
        f"<th>{html.escape(_t(langue, 'ev_th_mime'))}</th>"
        f"<th>{html.escape(_t(langue, 'ev_th_hash'))}</th>"
        f"<th>{html.escape(_t(langue, 'ev_th_size'))}</th>"
        f"<th>{html.escape(_t(langue, 'ev_th_by'))}</th>"
        f"</tr></thead><tbody>{rows}</tbody></table>"
    )


def render_engagement_letter(*, client: dict, prestataire: dict | None, audit: dict,
                             engagement: dict, scenario: dict | None,
                             applications: list[dict], auditeurs: list[dict],
                             tlp: str, langue: str = "fr") -> str:
    """Lettre d'engagement complète (cahier §5.A) : reprend l'intégralité du bloc
    `audit.engagement` saisi dans l'outil, plus les métadonnées de mission (audit,
    scénario, applications ciblées, équipe assignée, organisations)."""
    client_name = client.get("nom", "")
    presta_name = (prestataire or {}).get("nom") or "Prestataire Purple Team"

    # Applications ciblées : tableau criticité/exposition.
    app_rows = "".join(
        f"<tr><td>{_esc(a.get('nom'))}</td><td>{_esc(a.get('version')) or '—'}</td>"
        f"<td>{_esc(a.get('criticite')) or '—'}</td><td>{_esc(a.get('exposition')) or '—'}</td>"
        f"<td>{_esc(a.get('environnement') or audit.get('environnement')) or '—'}</td></tr>"
        for a in applications
    )
    apps_html = (
        f"<table><thead><tr><th>{_t(langue, 'eng_th_app')}</th><th>{_t(langue, 'eng_th_version')}</th>"
        f"<th>{_t(langue, 'eng_th_crit')}</th><th>{_t(langue, 'eng_th_expo')}</th>"
        f"<th>{_t(langue, 'eng_th_env')}</th></tr></thead><tbody>{app_rows}</tbody></table>"
        if app_rows else f"<p>{_t(langue, 'eng_fb_apps')}</p>"
    )

    # Équipe assignée.
    team_rows = "".join(
        f"<tr><td>{_esc(r.get('nom'))}</td><td>{_esc(r.get('role')) or '—'}</td>"
        f"<td>{_esc(', '.join(r.get('competences') or [])) or '—'}</td>"
        f"<td>{_esc(r.get('contact')) or '—'}</td></tr>"
        for r in auditeurs
    )
    team_html = (
        f"<table><thead><tr><th>{_t(langue, 'eng_th_member')}</th><th>{_t(langue, 'eng_th_role')}</th>"
        f"<th>{_t(langue, 'eng_th_skills')}</th><th>{_t(langue, 'eng_th_contact')}</th>"
        f"</tr></thead><tbody>{team_rows}</tbody></table>"
        if team_rows else f"<p>{_t(langue, 'eng_fb_team')}</p>"
    )

    # Contexte scénario (Purple/Red) le cas échéant.
    scenario_html = ""
    if scenario:
        techniques = scenario.get("techniques") or []
        tech_pills = "".join(f'<span class="pill">{_esc(t)}</span>' for t in techniques[:12])
        more = f" <span class='meta'>(+{len(techniques)-12})</span>" if len(techniques) > 12 else ""
        scenario_html = (
            f"<h2>3. {_t(langue, 'eng_h_scenario')}</h2>"
            + _kv_table([
                (_t(langue, "eng_kv_scenario"), _esc(scenario.get("nom"))),
                (_t(langue, "eng_kv_actor"), _esc(scenario.get("acteur_emule")) or "—"),
                (_t(langue, "eng_kv_engtype"), _esc(scenario.get("type_engagement")) or "—"),
                (_t(langue, "eng_kv_sophis"), _esc(scenario.get("sophistication")) or "—"),
                (_t(langue, "eng_kv_objective"), _esc(scenario.get("objectif")) or "—"),
            ])
            + (f"<h3>{_t(langue, 'eng_h_ttp')}</h3><p>{tech_pills}{more}</p>" if tech_pills else "")
        )

    referentiels = ", ".join(audit.get("referentiels_methodo") or []) or "PTES"
    sec = 4 if scenario else 3  # numérotation dynamique des sections suivantes

    autorisation_callout = (
        ""
        if engagement.get("autorisation_signee")
        else f'<div class="callout">{_t(langue, "eng_callout")}</div>'
    )
    perimetre_exclus_html = _ul(engagement.get("perimetre_exclus"), _t(langue, "eng_fb_excl"))

    # Métadonnées et blocs précalculés (évite l'imbrication de guillemets dans le gabarit).
    tt = (" · " + _esc(audit.get("type_test"))) if audit.get("type_test") else ""
    meta = _t(langue, "eng_meta").format(
        nom=_esc(audit.get("nom")), cat=_esc(audit.get("categorie")), tt=tt, refs=_esc(referentiels)
    )
    client_val = _esc(client_name) + (
        _t(langue, "eng_kv_siren").format(siren=_esc(client.get("siren"))) if client.get("siren") else ""
    )
    parties_kv = _kv_table([
        (_t(langue, "eng_kv_provider"), _esc(presta_name)),
        (_t(langue, "eng_kv_client"), client_val),
        (_t(langue, "eng_kv_sector"), _esc(client.get("secteur")) or "—"),
        (_t(langue, "eng_kv_contact"), _esc(client.get("referent_interne")) or "—"),
        (_t(langue, "eng_kv_sow"), _esc(engagement.get("sow")) or "—"),
        (_t(langue, "eng_kv_nda"), _esc(engagement.get("ref_nda")) or "—"),
        (_t(langue, "eng_kv_auth"),
         _t(langue, "yes") if engagement.get("autorisation_signee") else _t(langue, "eng_auth_no")),
    ])
    windows_kv = _kv_table([
        (_t(langue, "eng_kv_dates"), f"{_dt(audit.get('date_debut'))} → {_dt(audit.get('date_fin'))}"),
        (_t(langue, "eng_kv_env"), _esc(audit.get("environnement")) or "—"),
        (_t(langue, "eng_kv_intensity"),
         _esc(engagement.get("niveau_intensite")) or _t(langue, "eng_intensity_std")),
    ])
    roe_html = _para(engagement.get("regles_engagement"), _t(langue, "eng_fb_roe").format(refs=referentiels))
    legal_html = _para(engagement.get("clauses_legales"), _t(langue, "eng_fb_legal"))
    footer = _t(langue, "footer_parties").format(tlp=_esc(tlp))

    return f"""<!DOCTYPE html><html><head><meta charset="utf-8">{_BASE_CSS}</head><body>
    {_banner(tlp, client_name)}
    <h1>{_t(langue, 'eng_title')}</h1>
    <p class="meta">{meta}</p>

    <h2>1. {_t(langue, 'eng_h_parties')}</h2>
    {parties_kv}
    {autorisation_callout}

    <h2>2. {_t(langue, 'eng_h_scope')}</h2>
    <h3>{_t(langue, 'eng_h_objectives')}</h3>
    {_ul(engagement.get('objectifs'), _t(langue, 'eng_fb_objectives'))}
    <h3>{_t(langue, 'eng_h_incl')}</h3>
    {_ul(engagement.get('perimetre_inclus'), _t(langue, 'eng_fb_incl'))}
    <h3>{_t(langue, 'eng_h_excl')}</h3>
    {perimetre_exclus_html}
    <h3>{_t(langue, 'eng_h_apps')}</h3>
    {apps_html}

    {scenario_html}

    <h2>{sec}. {_t(langue, 'eng_h_windows')}</h2>
    {windows_kv}
    <h3>{_t(langue, 'eng_h_windows_ok')}</h3>
    {_ul(engagement.get('fenetres_test'), _t(langue, 'eng_fb_windows'))}

    <h2>{sec+1}. {_t(langue, 'eng_h_roe')}</h2>
    {roe_html}

    <h2>{sec+2}. {_t(langue, 'eng_h_contacts')}</h2>
    <h3>{_t(langue, 'eng_h_contacts_auth')}</h3>
    {_ul(engagement.get('contacts_autorisation'), _t(langue, 'eng_fb_contacts'))}
    <h3>{_t(langue, 'eng_h_contacts_urg')}</h3>
    {_ul(engagement.get('contacts_urgence'), _t(langue, 'eng_fb_contacts'))}

    <h2>{sec+3}. {_t(langue, 'eng_h_team')}</h2>
    {team_html}

    <h2>{sec+4}. {_t(langue, 'eng_h_deliverables')}</h2>
    {_ul(engagement.get('livrables_attendus'), _t(langue, 'eng_fb_deliverables'))}

    <h2>{sec+5}. {_t(langue, 'eng_h_legal')}</h2>
    {legal_html}

    {_sig_block(presta_name, client_name, langue)}
    <div class="footer">{footer}</div>
    </body></html>"""


def render_nda(*, client: dict, prestataire: dict | None, engagement: dict,
               audit: dict | None, tlp: str, langue: str = "fr") -> str:
    """Accord de confidentialité complet : reprend les cinq clauses NDA saisies dans
    le bloc engagement (objet, durée, traitement, restitution, droit applicable)."""
    client_name = client.get("nom", "")
    presta_name = (prestataire or {}).get("nom") or "Prestataire Purple Team"
    engagement = engagement or {}
    mission = _esc((audit or {}).get("nom")) if audit else ""

    meta_html = (
        f'<p class="meta">{_t(langue, "nda_meta").format(mission=mission)}</p>' if mission else ""
    )
    client_val = _esc(client_name) + (
        _t(langue, "eng_kv_siren").format(siren=_esc(client.get("siren"))) if client.get("siren") else ""
    )
    parties_kv = _kv_table([
        (_t(langue, "nda_kv_role"), _t(langue, "nda_role_recip")),
        (_t(langue, "nda_kv_provider"), _esc(presta_name)),
        (_t(langue, "nda_kv_client"), client_val),
        (_t(langue, "nda_kv_ref"), _esc(engagement.get("ref_nda")) or "—"),
    ])
    tlp_body = _t(langue, "nda_tlp_body").format(tlp=_esc(tlp))
    footer = _t(langue, "footer_parties").format(tlp=_esc(tlp))

    return f"""<!DOCTYPE html><html><head><meta charset="utf-8">{_BASE_CSS}</head><body>
    {_banner(tlp, client_name)}
    <h1>{_t(langue, 'nda_title')}</h1>
    {meta_html}

    <h2>1. {_t(langue, 'nda_h_parties')}</h2>
    {parties_kv}

    <h2>2. {_t(langue, 'nda_h_object')}</h2>
    {_para(engagement.get('nda_objet'), _t(langue, 'nda_fb_object'))}

    <h2>3. {_t(langue, 'nda_h_duration')}</h2>
    {_para(engagement.get('nda_duree'), _t(langue, 'nda_fb_duration'))}

    <h2>4. {_t(langue, 'nda_h_treatment')}</h2>
    {_para(engagement.get('nda_traitement'), _t(langue, 'nda_fb_treatment'))}

    <h2>5. {_t(langue, 'nda_h_return')}</h2>
    {_para(engagement.get('nda_restitution'), _t(langue, 'nda_fb_return'))}

    <h2>6. {_t(langue, 'nda_h_law')}</h2>
    {_para(engagement.get('nda_droit'), _t(langue, 'nda_fb_law'))}

    <h2>7. {_t(langue, 'nda_h_tlp')}</h2>
    <p>{tlp_body}</p>

    {_sig_block(presta_name, client_name, langue)}
    <div class="footer">{footer}</div>
    </body></html>"""


def _pct(v) -> str | None:
    """Formate un score 0–1 (EPSS) en pourcentage, None si absent."""
    if v in (None, ""):
        return None
    try:
        return f"{float(v) * 100:.1f}%"
    except (TypeError, ValueError):
        return None


def _vuln_evidence_table(items: list[dict], previews: dict[str, str], langue: str) -> str:
    """Tableau des preuves associées à une vulnérabilité, avec aperçu image inline."""
    if not items:
        return f"<p class='meta'>{html.escape(_t(langue, 'vd_no_evidence'))}</p>"
    rows = ""
    for e in items:
        eid = str(e.get("id"))
        sha = e.get("sha256_plaintext")
        sha_cell = f'<span class="mono">{html.escape(sha)}</span>' if sha else "—"
        if eid in previews:
            # data URI issu du serveur (preuve déchiffrée) — inséré tel quel.
            preview_cell = f'<img class="ev-preview" src="{previews[eid]}" alt="">'
        elif e.get("contains_secrets"):
            preview_cell = f'<span class="masked">{html.escape(_t(langue, "vd_ev_masked_preview"))}</span>'
        else:
            preview_cell = "—"
        rows += (
            "<tr>"
            f"<td class='mono nowrap'>{_ts(e.get('uploaded_at'))}</td>"
            f"<td>{_mask_if_secret(e, langue)}</td>"
            f"<td class='mono'>{_esc(e.get('detected_mime')) or '—'}</td>"
            f"<td class='hash'>{sha_cell}</td>"
            f"<td class='nowrap'>{_human_size(e.get('size_bytes'), langue)}</td>"
            f"<td>{preview_cell}</td>"
            "</tr>"
        )
    return (
        '<table class="vuln-evidence"><thead><tr>'
        f"<th>{html.escape(_t(langue, 'ev_th_ts'))}</th>"
        f"<th>{html.escape(_t(langue, 'ev_th_name'))}</th>"
        f"<th>{html.escape(_t(langue, 'ev_th_mime'))}</th>"
        f"<th>{html.escape(_t(langue, 'ev_th_hash'))}</th>"
        f"<th>{html.escape(_t(langue, 'ev_th_size'))}</th>"
        f"<th>{html.escape(_t(langue, 'vd_ev_th_preview'))}</th>"
        f"</tr></thead><tbody>{rows}</tbody></table>"
    )


def _vuln_prose(finding: dict, field_key: str, label_key: str, langue: str) -> str:
    """Bloc de texte libre (description, impact, reco…) d'une vulnérabilité, si renseigné."""
    val = finding.get(field_key)
    if not val:
        return ""
    return f"<h4>{_t(langue, label_key)}</h4><div class='vuln-prose'>{_esc(val)}</div>"


def _vuln_details(findings: list[dict], evidence: list[dict],
                  previews: dict[str, str], langue: str) -> str:
    """Fiche détaillée par vulnérabilité : toutes les métadonnées saisies par l'auditeur
    + tableau des preuves associées (liées par finding_id, référencées par empreinte) avec
    aperçu inline pour les images non secrètes."""
    if not findings:
        return f"<p>{html.escape(_t(langue, 'vd_none'))}</p>"
    # Regroupement des preuves par vulnérabilité (finding_id).
    ev_by_finding: dict[str, list[dict]] = {}
    for e in evidence:
        fid = e.get("finding_id")
        if fid:
            ev_by_finding.setdefault(str(fid), []).append(e)

    cards = ""
    for f in findings:
        sev = str(f.get("severite") or "info").lower()
        sub_bits = [b for b in (_esc(f.get("cve")), _esc(f.get("cwe")),
                                (f"TLP:{_esc(f.get('tlp'))}" if f.get("tlp") else "")) if b]
        sub = " · ".join(sub_bits)

        # Métadonnées : uniquement les champs renseignés (fiche lisible).
        epss = _pct(f.get("epss"))
        epss_pct = _pct(f.get("epss_percentile"))
        epss_val = None
        if epss:
            epss_val = epss + (f" (percentile {epss_pct})" if epss_pct else "")
        kev_val = None
        if f.get("kev"):
            kev_val = _t(langue, "yes") + (
                f" · {_t(langue, 'vd_kev_ransom')}" if f.get("kev_ransomware") else ""
            )
        candidate_rows = [
            (_t(langue, "vd_kv_cvss"), _esc(f.get("cvss_score"))),
            (_t(langue, "vd_kv_vector"), _esc(f.get("cvss_vector"))),
            ("OWASP Top 10", _esc(f.get("owasp_top10"))),
            (_t(langue, "vd_kv_status"), _esc(f.get("statut"))),
            (_t(langue, "vd_kv_exploit"), _esc(f.get("exploitabilite"))),
            (_t(langue, "vd_kv_phase"), _esc(f.get("phase_decouverte"))),
            (_t(langue, "vd_kv_discoverer"), _esc(f.get("decouvreur_nom"))),
            (_t(langue, "vd_kv_sla"), _esc(f.get("sla_niveau"))),
            (_t(langue, "vd_kv_sla_due"), _dt(f.get("sla_echeance")) if f.get("sla_echeance") else ""),
            (_t(langue, "vd_kv_epss"), epss_val or ""),
            (_t(langue, "vd_kv_kev"), kev_val or ""),
            (_t(langue, "vd_kv_ssvc"), _esc(f.get("ssvc_decision"))),
            (_t(langue, "vd_kv_vex"), _esc(f.get("vex_status"))),
        ]
        kv_rows = [(k, v) for k, v in candidate_rows if v]
        meta_kv = _kv_table(kv_rows) if kv_rows else ""

        techniques = f.get("techniques") or []
        ttp = "".join(f'<span class="pill">{_esc(t)}</span>' for t in techniques)
        ttp_html = f"<h4>{_t(langue, 'vd_h_ttp')}</h4><p>{ttp}</p>" if ttp else ""
        d3 = f.get("d3fend") or []
        d3_pills = "".join(f'<span class="pill">{_esc(x)}</span>' for x in d3)
        d3_html = f"<h4>{_t(langue, 'vd_h_d3fend')}</h4><p>{d3_pills}</p>" if d3_pills else ""

        ev_items = ev_by_finding.get(str(f.get("id")), [])
        cards += (
            '<div class="vuln-card">'
            f'<h3>{_esc(f.get("titre")) or "—"} '
            f'<span class="sev-badge {sev}">{_esc(f.get("severite")) or sev}</span></h3>'
            + (f'<p class="sub">{sub}</p>' if sub else "")
            + meta_kv
            + _vuln_prose(f, "description", "vd_h_desc", langue)
            + _vuln_prose(f, "impact_metier", "vd_h_impact", langue)
            + _vuln_prose(f, "preuve_exploitation", "vd_h_proof", langue)
            + _vuln_prose(f, "recommandation", "vd_h_reco", langue)
            + ttp_html + d3_html
            + f"<h4>{_t(langue, 'vd_h_evidence')}</h4>"
            + _vuln_evidence_table(ev_items, previews, langue)
            + "</div>"
        )
    return cards


def render_ptes_report(*, client: dict, prestataire: dict | None, audit: dict,
                       scenario: dict | None, applications: list[dict],
                       auditeurs: list[dict], actions: list[dict],
                       findings: list[dict], evidence: list[dict], tlp: str,
                       langue: str = "fr", previews: dict[str, str] | None = None,
                       preview_max_bytes: int = 0) -> str:
    """Rapport PTES complet. Les preuves secrètes restent masquées (porte 5)."""
    previews = previews or {}
    client_name = client.get("nom", "")
    presta_name = (prestataire or {}).get("nom") or "Prestataire Purple Team"
    referentiels = ", ".join(audit.get("referentiels_methodo") or []) or "PTES"

    # ── Synthèse chiffrée par sévérité ── (les libellés de sévérité restent des codes métier)
    sev_order = ["critique", "haute", "moyenne", "basse", "info"]
    sev_count: dict[str, int] = {}
    for f in findings:
        s = str(f.get("severite") or "info").lower()
        sev_count[s] = sev_count.get(s, 0) + 1
    stat_cells = "".join(
        f"<td class='sev-{s}'><strong>{sev_count.get(s, 0)}</strong> {s}</td>"
        for s in sev_order if s in sev_count
    ) or f"<td>{_t(langue, 'rpt_no_vuln')}</td>"

    # ── Vulnérabilités détaillées ──
    rows = "".join(
        f"<tr><td>{_esc(f.get('titre'))}"
        + (f"<br><span class='meta'>{_esc(f.get('cve'))}</span>" if f.get('cve') else "")
        + f"</td><td>{_esc(f.get('cvss_score')) or '—'}</td>"
        f"<td class='sev-{_esc(str(f.get('severite','')).lower())}'>{_esc(f.get('severite')) or '—'}</td>"
        f"<td>{_esc(f.get('epss')) or '—'}</td>"
        f"<td>{_t(langue, 'yes') if f.get('kev') else '—'}</td>"
        f"<td>{_esc(f.get('sla_niveau')) or '—'}</td>"
        f"<td>{_esc(f.get('statut')) or '—'}</td></tr>"
        for f in findings
    )

    # ── Actions d'audit par phase PTES ──
    actions_html = ""
    if actions:
        act_rows = "".join(
            f"<tr><td>{_esc(a.get('ptes_phase')) or '—'}</td><td>{_esc(a.get('titre'))}</td>"
            f"<td>{_esc(a.get('technique_attack')) or '—'}</td>"
            f"<td>{_esc(a.get('outil')) or '—'}</td>"
            f"<td>{_esc(a.get('resultat')) or '—'}</td></tr>"
            for a in actions
        )
        actions_html = (
            f"<h2>{_t(langue, 'rpt_h_actions')}</h2>"
            f"<table><thead><tr><th>{_t(langue, 'rpt_th_phase')}</th><th>{_t(langue, 'rpt_th_action')}</th>"
            f"<th>ATT&amp;CK</th><th>{_t(langue, 'rpt_th_tool')}</th>"
            f"<th>{_t(langue, 'rpt_th_result')}</th></tr></thead><tbody>{act_rows}</tbody></table>"
        )

    # ── Contexte scénario ──
    scenario_html = ""
    if scenario:
        techniques = scenario.get("techniques") or []
        tech_pills = "".join(f'<span class="pill">{_esc(t)}</span>' for t in techniques[:16])
        more = f" <span class='meta'>(+{len(techniques)-16})</span>" if len(techniques) > 16 else ""
        scenario_html = (
            f"<h2>{_t(langue, 'rpt_h_scenario')}</h2>"
            + _kv_table([
                (_t(langue, "rpt_kv_scenario"), _esc(scenario.get("nom"))),
                (_t(langue, "rpt_kv_actor"), _esc(scenario.get("acteur_emule")) or "—"),
                (_t(langue, "rpt_kv_sophis"), _esc(scenario.get("sophistication")) or "—"),
                (_t(langue, "rpt_kv_objective"), _esc(scenario.get("objectif")) or "—"),
            ])
            + (f"<p>{tech_pills}{more}</p>" if tech_pills else "")
        )

    # ── Périmètre applicatif ──
    app_rows = "".join(
        f"<tr><td>{_esc(a.get('nom'))}</td><td>{_esc(a.get('criticite')) or '—'}</td>"
        f"<td>{_esc(a.get('exposition')) or '—'}</td><td>{_esc(a.get('stack')) or '—'}</td></tr>"
        for a in applications
    )
    apps_html = (
        f"<h2>{_t(langue, 'rpt_h_apps')}</h2><table><thead><tr><th>{_t(langue, 'rpt_th_app')}</th>"
        f"<th>{_t(langue, 'rpt_th_crit')}</th><th>{_t(langue, 'rpt_th_expo')}</th>"
        f"<th>{_t(langue, 'rpt_th_stack')}</th></tr></thead><tbody>{app_rows}</tbody></table>"
    ) if app_rows else ""

    team = ", ".join(_esc(r.get("nom")) for r in auditeurs) or "—"
    evidence_register = _evidence_register(evidence, langue)
    categorie_type_test = _esc(audit.get("categorie")) + (
        f" · {_esc(audit.get('type_test'))}" if audit.get("type_test") else ""
    )
    mission_kv = _kv_table([
        (_t(langue, "rpt_kv_client"), _esc(client_name)),
        (_t(langue, "rpt_kv_provider"), _esc(presta_name)),
        (_t(langue, "rpt_kv_cat"), categorie_type_test),
        (_t(langue, "rpt_kv_refs"), _esc(referentiels)),
        (_t(langue, "rpt_kv_period"), f"{_dt(audit.get('date_debut'))} → {_dt(audit.get('date_fin'))}"),
        (_t(langue, "rpt_kv_env"), _esc(audit.get("environnement")) or "—"),
        (_t(langue, "rpt_kv_team"), team),
        (_t(langue, "rpt_kv_status"), _esc(audit.get("statut")) or "—"),
    ])
    report_meta = _t(langue, "rpt_meta").format(
        nom=_esc(audit.get("nom")), client=_esc(client_name), presta=_esc(presta_name)
    )
    vuln_rows = rows or f"<tr><td colspan=7>{_t(langue, 'rpt_none')}</td></tr>"
    vuln_details_html = _vuln_details(findings, evidence, previews, langue)
    preview_limit_note = ""
    if preview_max_bytes:
        preview_limit_note = (
            f'<p class="meta">{_t(langue, "vd_preview_limit").format(size=_human_size(preview_max_bytes, langue))}</p>'
        )
    footer = _t(langue, "footer_client").format(tlp=_esc(tlp))

    return f"""<!DOCTYPE html><html><head><meta charset="utf-8">{_BASE_CSS}</head><body>
    {_banner(tlp, client_name)}
    <h1>{_t(langue, 'rpt_title')}</h1>
    <p class="meta">{report_meta}</p>

    <h2>{_t(langue, 'rpt_h_mission')}</h2>
    {mission_kv}

    <h2>{_t(langue, 'rpt_h_summary')}</h2>
    <table><tbody><tr>{stat_cells}</tr></tbody></table>

    {scenario_html}
    {apps_html}
    {actions_html}

    <h2>{_t(langue, 'rpt_h_vulns')}</h2>
    <table><thead><tr><th>{_t(langue, 'rpt_th_vuln')}</th><th>CVSS</th>
    <th>{_t(langue, 'rpt_th_sev')}</th><th>EPSS</th>
    <th>KEV</th><th>SLA</th><th>{_t(langue, 'rpt_th_status')}</th></tr>
    </thead><tbody>{vuln_rows}</tbody></table>

    <h2>{_t(langue, 'vd_h_section')}</h2>
    {preview_limit_note}
    {vuln_details_html}

    <h2>{_t(langue, 'rpt_h_evidence')}</h2>
    {evidence_register}
    <p class="meta">{_t(langue, 'rpt_evidence_note')}</p>

    <div class="footer">{footer}</div>
    </body></html>"""


async def html_to_pdf(html_content: str) -> bytes:
    """Convertit le HTML en PDF via le service Chromium headless (pdf-renderer).

    En cas d'échec du renderer, on LÈVE une erreur au lieu de renvoyer le HTML :
    stocker du HTML sous une extension .pdf produit un fichier corrompu (le bug
    observé). Le pipeline reste testable via un renderer réel ou un mock explicite.
    """
    import httpx

    from app.config import settings

    renderer_url = getattr(settings, "pdf_renderer_url", "http://pdf-renderer:3000/pdf")
    async with httpx.AsyncClient(timeout=30) as http:
        resp = await http.post(renderer_url, json={"html": html_content})
        resp.raise_for_status()  # 503 du renderer → RuntimeError remonté à l'appelant
        ctype = resp.headers.get("content-type", "")
        if "application/pdf" not in ctype:
            # Garde-fou : ne jamais laisser passer autre chose qu'un vrai PDF.
            raise RuntimeError(
                f"pdf-renderer a renvoyé {ctype!r} au lieu d'un PDF — rendu indisponible"
            )
        return resp.content


# ── Micro-service de rendu (service `pdf-renderer` du compose) ───────────────
# Le modèle DOIT être défini au niveau module : un BaseModel déclaré dans une
# closure (à l'intérieur de _build_render_app) n'est pas reconnu de façon fiable
# par FastAPI comme corps de requête — il le traite alors en paramètre query,
# renvoyant 422 "Field required (query, req)" même sur un POST JSON valide.
# C'était la cause du 422 systématique du renderer.
class RenderRequest(BaseModel):
    # Corps attendu : {"html": "<...>"}. Champ tolérant (défaut vide) : le contrôle
    # "html vide" est fait explicitement dans le endpoint, avec un message clair.
    html: str = ""


def _build_render_app():
    """Application FastAPI minimale exposant POST /pdf.

    Rend un vrai PDF via Playwright/Chromium. En cas d'indisponibilité du moteur,
    renvoie une erreur explicite (503) — JAMAIS du HTML déguisé en PDF (qui serait
    stocké tel quel sous une extension .pdf). Cette séparation garde le rendu hors
    du processus API (isolation, ressources).
    """
    render_app = FastAPI(title="pdf-renderer")

    @render_app.get("/health")
    async def _health():
        return {"status": "ok"}

    @render_app.post("/pdf")
    async def _pdf(req: RenderRequest):
        html_content = req.html
        if not html_content.strip():
            return Response(
                content=b"empty_html", media_type="text/plain", status_code=422
            )
        try:
            from playwright.async_api import async_playwright  # type: ignore

            async with async_playwright() as p:
                browser = await p.chromium.launch(args=["--no-sandbox"])
                page = await browser.new_page()
                await page.set_content(html_content, wait_until="networkidle")
                pdf = await page.pdf(format="A4", print_background=True)
                await browser.close()
            return Response(content=pdf, media_type="application/pdf")
        except Exception as exc:
            # NE JAMAIS renvoyer le HTML déguisé en succès : l'appelant le
            # stockerait sous .pdf (fichier corrompu). Échec franc → l'API
            # remonte l'erreur au lieu de produire un faux PDF.
            import logging

            logging.getLogger("pdf-renderer").error(
                "rendu Chromium indisponible (%s) — vérifier `playwright install "
                "chromium` dans l'image", exc, exc_info=True,
            )
            return Response(
                content=b"pdf_renderer_unavailable",
                media_type="text/plain",
                status_code=503,
            )

    return render_app


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(_build_render_app(), host="0.0.0.0", port=3000)
